In [1]:
import numpy as np

In [2]:
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

In [3]:
#Q1
type(list_) 

list

In [4]:
type(array_list)

numpy.ndarray

In [5]:
#Q2
array_list.dtype

dtype('<U1')

In [6]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
#Q3
array_list = np.array(object = list_, dtype = int)

In [8]:
array_list.dtype

dtype('int32')

In [9]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
type(list_)

list

yes the srting is converted into integer in array_list,but list_ is not changed.

In [11]:
#Q4
arr1=np.random.randint(1,6,(4,3))

In [12]:
arr1

array([[3, 3, 5],
       [1, 3, 4],
       [3, 1, 5],
       [4, 4, 2]])

In [13]:
arr1.size

12

In [14]:
arr1.shape

(4, 3)

In [15]:
#Q5
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
#Q6
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])